version: "3.8"

services:
  bot:
    build: ./
    volumes:
      - /app/node_modules
    ports:
      - "45313:45313"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:45313/status"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 10s